import {SEED,KANBAN} from './data.js';
import {loadData,saveData,resetData,exportData,importData,uid,hydrateData} from './storage.js';
import {authenticatePin} from './auth.js';
import {esc,toast} from './utils.js';
import {sidebar,topbar,modal,clientCard} from './components.js';
import {kanban,bindDrag} from './kanban.js';
import {getRoute,go} from './router.js';

let data=loadData(SEED);let user=data.session?.role?data.session:null;let selected=data.clients[0]?.id;const app=document.querySelector('#app');
const persist=(sync=true)=>saveData(data,{sync});
const recalc=c=>{c.items=c.tasks.length;c.progress=c.tasks.length?Math.round(c.tasks.reduce((sum,t)=>sum+(t.status==='Concluído'?100:Number(t.progress)||0),0)/c.tasks.length):0};

function login(){let pin='';app.innerHTML=`<main class="pin-login"><section class="pin-card"><img class="pin-logo" src="assets/images/studio-cora-logo.svg" alt="STUDIO CORA"><p class="pin-kicker">ACESSO RESTRITO</p><h1>Digite seu código</h1><p class="pin-hint">Administradora ou noiva, informe seu PIN para desbloquear o espaço.</p><div class="pin-display" id="pin-display"><i></i><i></i><i></i><i></i></div><div class="pin-pad">${[1,2,3,4,5,6,7,8,9].map(n=>`<button data-key="${n}">${n}</button>`).join('')}<button data-action="clear">C</button><button data-key="0">0</button><button data-action="back">⌫</button></div><p class="pin-error" id="pin-error"></p></section></main>`;const display=()=>{document.querySelectorAll('#pin-display i').forEach((dot,i)=>dot.classList.toggle('filled',i<pin.length))};const submit=()=>{const found=authenticatePin(pin,data.clients);if(!found){document.querySelector('#pin-error').textContent='Código não reconhecido.';pin='';display();return}user={...found,pin};data.session=user;persist(false);render()};document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>{if(pin.length<4){pin+=b.dataset.key;display();if(pin.length===4)setTimeout(submit,120)}});document.querySelector('[data-action="clear"]').onclick=()=>{pin='';display()};document.querySelector('[data-action="back"]').onclick=()=>{pin=pin.slice(0,-1);display()}}

function layout(title,below=''){app.innerHTML=`<div class="app-shell">${sidebar(getRoute(),user.role,user.role==='client'?data.clients.find(c=>c.id===user.clientId)?.name||'Cliente':'')}<div class="main">${topbar(title,user.role==='admin'?'PAINEL ADMINISTRATIVO':'',below)}<main class="content" id="view"></main></div></div>`;const drawer=document.querySelector('#sidebar'),toggle=()=>{const open=!drawer.classList.contains('open');drawer.classList.toggle('open',open);const button=document.querySelector('#mobile-menu-toggle');if(button){button.setAttribute('aria-expanded',String(open));button.setAttribute('aria-label',open?'Fechar menu':'Abrir menu')}};document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{drawer?.classList.remove('open');go(b.dataset.route)});document.querySelector('#mobile-menu-toggle')?.addEventListener('click',toggle);document.querySelector('#mobile-menu-close')?.addEventListener('click',()=>drawer?.classList.remove('open'));document.querySelector('#logout').onclick=()=>{data.session=null;persist(false);user=null;login()}}

function boardCard(task,client,general=false){return `<article class="task-card" draggable="true" data-task="${task.id}" data-client="${client.id}" data-open-task="${task.id}"><h4>${esc(task.title)}</h4><p class="task-client">${esc(client.couple||client.name)}</p><p>${esc(task.currentDescription||task.desc||'Nenhuma descrição adicionada.')}</p><div class="task-foot"><span>Clique para ver detalhes</span>${general?`<button type="button" class="task-delete" data-delete-task="${task.id}" aria-label="Apagar card">×</button>`:""}</div></article>`}
function board(columns,items,general=false){return `<div class="kanban">${columns.map(status=>{const list=items.filter(x=>x.task.status===status);return `<section class="kanban-col" data-status="${status}"><div class="col-head"><strong>${status}</strong><span class="count">${list.length}</span></div>${list.map(x=>boardCard(x.task,x.client,general)).join('')||'<div class="empty" style="padding:20px 5px;font-size:11px">Nenhum item</div>'}</section>`}).join('')}</div>`}
function generalKanban(){layout('Kanban geral');const items=data.clients.flatMap(client=>client.tasks.map(task=>({task,client})));document.querySelector('#view').innerHTML=`<div class="section-head"><div><p class="muted">Todos os itens de todas as noivas em um só lugar. Ao mover um card, o Kanban individual também é atualizado.</p></div><button class="btn btn-primary" id="new-general-task">+ Novo item</button></div>${board(KANBAN,items,true)}`;bindDrag(document.querySelector('#view'),(id,status,clientId)=>moveTask(id,status,clientId,true));bindTaskClicks(document.querySelector('#view'));bindDeleteTaskButtons(document.querySelector('#view'));document.querySelector('#new-general-task').onclick=()=>newTaskModal()}
function moveTask(id,status,clientId,refreshGeneral=false){const c=data.clients.find(x=>x.id===clientId),t=c?.tasks.find(x=>x.id===id);if(!t)return;const old=t.status;t.status=status;t.history=t.history||[];if(old!==status)t.history.push({status,date:new Date().toISOString()});recalc(c);persist();toast('Etapa atualizada');refreshGeneral?generalKanban():project()}
function bindDeleteTaskButtons(root){root.querySelectorAll('[data-delete-task]').forEach(button=>button.addEventListener('click',e=>{e.stopPropagation();const card=button.closest('[data-client]'),client=data.clients.find(c=>c.id===card?.dataset.client)||data.clients.find(c=>c.id===selected),task=client?.tasks.find(t=>t.id===button.dataset.deleteTask);if(!client||!task||!confirm('Apagar '+task.title+'? Esta ação não pode ser desfeita.'))return;client.tasks=client.tasks.filter(t=>t.id!==task.id);recalc(client);persist();toast('Card apagado');getRoute()==='project'?project():generalKanban()}))}
function bindTaskClicks(root){root.querySelectorAll('[data-open-task]').forEach(card=>card.addEventListener('click',e=>{if(e.target.closest('[draggable]')&&e.detail===0)return;const client=data.clients.find(c=>c.id===card.dataset.client)||data.clients.find(c=>c.id===selected);const task=client?.tasks.find(t=>t.id===card.dataset.openTask);if(task)openTaskModal(client,task)}))}
function openTaskModal(client,task){const history=(task.history||[]).map(h=>`<div class="history-row"><span>${esc(h.status)}</span><small>${new Date(h.date).toLocaleDateString('pt-BR')}</small></div>`).join('')||'<p class="muted">Nenhuma mudança registrada ainda.</p>';const editable=user.role==='admin';document.body.insertAdjacentHTML('beforeend',modal('Detalhes do item',`<form id="task-detail-form"><div class="field"><label>Nome do item</label><input name="title" value="${esc(task.title)}" ${editable?'':'disabled'}></div><div class="field" style="margin-top:13px"><label>O que está sendo feito agora</label><textarea name="currentDescription" ${editable?'':'disabled'}>${esc(task.currentDescription||task.desc||'')}</textarea></div><div class="field" style="margin-top:18px"><label>Histórico de etapas</label><div class="task-history">${history}</div></div><div class="modal-actions"><button type="button" class="btn btn-ghost" data-close-modal>Fechar</button>${editable?'<button class="btn btn-primary">Salvar</button>':''}</div></form>`));document.querySelector('#task-detail-form').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));task.title=f.title;task.currentDescription=f.currentDescription;task.desc=f.currentDescription;persist();document.querySelector('#modal').remove();toast('Item atualizado');getRoute()==='project'?project():generalKanban()};document.querySelectorAll('[data-close-modal]').forEach(b=>b.onclick=()=>b.closest('.modal-backdrop').remove())}

function clients(){layout('Clientes');document.querySelector('#view').innerHTML=`<div class="section-head"><div><p class="muted">Acompanhe os cadastros e acesse o projeto de cada noiva.</p></div><button class="btn btn-primary" id="new-client">+ Nova cliente</button></div><div class="toolbar"><input class="search" id="client-search" placeholder="Buscar por nome ou casal..."><select id="status-filter"><option value="">Todos os status</option><option>Em andamento</option><option>Em fase final</option><option>Novo briefing</option></select></div><div class="clients-grid grid" id="clients-grid">${data.clients.map(clientCard).join('')}</div>`;const bind=()=>{document.querySelectorAll('[data-client]').forEach(b=>{if(b.classList.contains('task-edit'))return;b.onclick=()=>{selected=b.dataset.client;go('project')}});document.querySelectorAll('[data-edit-client]').forEach(b=>b.onclick=()=>newClientModal(data.clients.find(c=>c.id===b.dataset.editClient)));document.querySelectorAll('[data-archive-client]').forEach(b=>b.onclick=()=>{const c=data.clients.find(c=>c.id===b.dataset.archiveClient);if(!confirm('Apagar '+c.couple+'? Esta ação não pode ser desfeita.'))return;data.clients=data.clients.filter(x=>x.id!==c.id);if(selected===c.id)selected=data.clients[0]?.id;persist();toast('Cliente apagada');clients()})};const update=()=>{const q=document.querySelector('#client-search').value.toLowerCase(),s=document.querySelector('#status-filter').value;document.querySelector('#clients-grid').innerHTML=data.clients.filter(c=>(!q||`${c.name} ${c.couple}`.toLowerCase().includes(q))&&(!s||c.status===s)).map(clientCard).join('')||'<div class="empty card">Nenhuma cliente encontrada.</div>';bind()};document.querySelector('#client-search').oninput=update;document.querySelector('#status-filter').onchange=update;document.querySelector('#new-client').onclick=()=>newClientModal();bind()}
function newClientModal(c){const edit=!!c;document.body.insertAdjacentHTML('beforeend',modal(edit?'Editar cliente':'Nova cliente',`<form id="client-form"><div class="form-grid"><div class="field"><label>Nome da cliente <span>*</span></label><input name="name" required value="${esc(c?.name||'')}"></div><div class="field"><label>Nome do casal <span>*</span></label><input name="couple" required value="${esc(c?.couple||'')}"></div><div class="field"><label>E-mail</label><input name="email" type="email" value="${esc(c?.email||'')}"></div><div class="field"><label>Data do casamento</label><input name="wedding" type="date" value="${c?.wedding||''}"></div><div class="field full"><label>Local do casamento</label><input name="venue" value="${esc(c?.venue||'')}"></div></div><div class="modal-actions"><button type="button" class="btn btn-ghost" data-close-modal>Cancelar</button><button class="btn btn-primary">Salvar cliente</button></div></form>`));document.querySelector('#client-form').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(edit)Object.assign(c,f);else data.clients.push({id:uid('c'),...f,avatar:f.name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase(),progress:0,status:'Em andamento',briefing:'Pendente',last:'Agora',items:0,tasks:[],notes:''});persist();document.querySelector('#modal').remove();toast('Cliente salva');clients()};document.querySelectorAll('[data-close-modal]').forEach(b=>b.onclick=()=>b.closest('.modal-backdrop').remove())}

function project(){const c=data.clients.find(x=>x.id===selected)||data.clients[0];if(!c)return clients();if(user.role==='client')return clientProject(c);layout(c.couple);document.querySelector('#view').innerHTML=`<section class="profile-hero card"><div class="profile-name"><div class="client-avatar" style="width:58px;height:58px">${esc(c.avatar)}</div><div><div class="eyebrow">Perfil da cliente</div><h2>${esc(c.couple)}</h2><p>${esc(c.name)} · ${c.wedding||'Sem data'}</p></div></div><div class="profile-kpis"><div><strong>${c.progress||0}%</strong><small>progresso</small></div><div><strong>${c.tasks.length}</strong><small>itens</small></div></div></section><div class="tabs"><button class="tab active" data-tab="kanban">Kanban</button><button class="tab" data-tab="briefing">Briefing completo</button></div><div id="project-tab"></div>`;renderProjectTab(c,'kanban');document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProjectTab(c,b.dataset.tab)})}
function clientProject(c){layout('Portal da noiva',c.couple);document.querySelector('#view').innerHTML=`<div class="client-kanban-intro"><div class="eyebrow"><span class="portal-mobile-couple">${esc(c.couple)}</span><span class="portal-desktop-project">Meu projeto</span></div><p class="muted">Acompanhe o andamento dos itens do seu projeto.</p></div>${kanban(c,false)}`;bindTaskClicks(document.querySelector('#view'))}
function renderProjectTab(c,tab){const el=document.querySelector('#project-tab');if(tab==='kanban'){el.innerHTML=`<div class="section-head"><div><h3 class="section-title">Itens do projeto</h3><p class="muted">Crie e mova os itens deste Kanban.</p></div><button class="btn btn-primary" id="new-task">+ Novo item</button></div>${kanban(c,true)}`;bindDrag(el,(id,status)=>moveTask(id,status,c.id,false));bindTaskClicks(el);bindDeleteTaskButtons(el);document.querySelector('#new-task').onclick=()=>newTaskModal(c)}else{el.innerHTML=briefingDetails(c)}}
function briefingDetails(c){const b=c.briefingData||{};const labels={brideName:'Nome da cliente',email:'E-mail',couple:'Nome dos noivos',nameNotes:'Observações sobre os nomes',story:'História do casal',together:'Tempo juntos',personality:'Personalidade do casal',wedding:'Data do casamento',venue:'Local',city:'Cidade',time:'Horário',guests:'Convidados',dressCode:'Dress code',dressCodeOther:'Outro dress code','monograms-aquarela':'Monogramas · Aquarela','monograms-liso':'Monogramas · Liso',visual:'Estilo visual',palette:'Paleta desejada',avoidColors:'Cores que não deseja',communication:'Comunicação visual',inviteElements:'Elementos do convite',detailTechnique:'Pequenos detalhes',detailTechniqueOther:'Outro acabamento',personalStory:'História ou inspiração',notWanted:'O que não deseja',fonts:'Tipografia',nameTypography:'Tipografia dos nomes',fontOther:'Outro estilo tipográfico',links:'Referências',likes:'O que gostou',dislikes:'O que não gostou',channel:'Canal de contato',hours:'Melhor horário',approver:'Responsável pelas aprovações',additional:'Informações adicionais'};const entries=Object.entries(b).filter(([,v])=>v!==''&&v!==null&&v!==undefined);return `<section class="panel card briefing-response"><div class="panel-head"><div><h3>Briefing completo</h3><p class="muted">Todas as respostas enviadas pela cliente.</p></div><span class="badge badge-green">${c.briefing||'Completo'}</span></div>${entries.map(([key,value])=>`<div class="review-item"><strong>${labels[key]||key}</strong><p>${esc(Array.isArray(value)?value.join(', '):value)}</p></div>`).join('')||'<div class="empty">Nenhum briefing recebido.</div>'}</section>`}
function newTaskModal(client=null){document.body.insertAdjacentHTML('beforeend',modal('Novo item do Kanban',`<form id="task-form"><div class="form-grid">${client?'':`<div class="field full"><label>Cliente <span>*</span></label><select name="clientId" required>${data.clients.map(c=>`<option value="${c.id}">${esc(c.couple)}</option>`).join('')}</select></div>`}<div class="field full"><label>Nome do item <span>*</span></label><input name="title" required></div><div class="field full"><label>Descrição do que será feito</label><textarea name="currentDescription"></textarea></div></div><div class="modal-actions"><button type="button" class="btn btn-ghost" data-close-modal>Cancelar</button><button class="btn btn-primary">Criar item</button></div></form>`));document.querySelector('#task-form').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),c=client||data.clients.find(x=>x.id===f.clientId);if(!c)return;c.tasks.push({id:uid('t'),title:f.title,currentDescription:f.currentDescription,desc:f.currentDescription,status:'A desenvolver',history:[{status:'A desenvolver',date:new Date().toISOString()}]});recalc(c);persist();document.querySelector('#modal').remove();toast('Item criado');client?project():generalKanban()};document.querySelectorAll('[data-close-modal]').forEach(b=>b.onclick=()=>b.closest('.modal-backdrop').remove())}
function settings(){layout('Configurações');document.querySelector('#view').innerHTML=`<section class="panel card"><div class="panel-head"><h3>Dados e segurança local</h3></div><p class="muted">O PIN admin é 0909. Faça backups frequentes enquanto o sistema estiver usando LocalStorage.</p><button class="btn btn-soft" id="export">Exportar backup JSON</button> <button class="btn btn-ghost" id="reset">Restaurar demonstração</button><input type="file" id="import" accept="application/json" style="display:none"><button class="btn btn-ghost" id="import-btn">Importar backup</button></section>`;document.querySelector('#export').onclick=()=>exportData(data);document.querySelector('#reset').onclick=()=>{data=resetData(SEED);user=null;login()};document.querySelector('#import-btn').onclick=()=>document.querySelector('#import').click();document.querySelector('#import').onchange=async e=>{data=await importData(e.target.files[0]);toast('Backup importado');render()}}
function render(){if(!user)return login();if(user.role==='client'){selected=user.clientId;return project()}const r=getRoute();if(r==='dashboard'){go('kanban');return}if(r==='clients')clients();else if(r==='settings')settings();else if(r==='project')project();else generalKanban()}
window.addEventListener('hashchange',render);
hydrateData(SEED).then(remote=>{data=remote;user=data.session?.role?data.session:null;selected=data.clients[0]?.id;render()});



