import {SEED} from './data.js';
import {loadData,saveData,uid,hydrateData} from './storage.js';
import {toast,esc} from './utils.js';

let data,params,existingId,existing,KEY,saved,step=0;
const monograms={aquarela:[['vintage','Vintage','assets/images/monogram-2-vintage.png'],['serif','Serifa','assets/images/monogram-3-serif.png']],liso:[['limpo','Limpo','assets/images/monogram-5-clean.png'],['vitoriano','Vitoriano','assets/images/monogram-6-victorian.png'],['entrelaçado','Entrelaçado','assets/images/monogram-4-interlaced.png'],['brasão decorado','Brasão decorado','assets/images/monogram-7-ornate.png'],['brasão simples','Brasão simples','assets/images/monogram-8-simple.png']]};
const visualStyles=[['romantico','Romântico','assets/images/taste-01-romantico.png'],['tropical','Tropical','assets/images/taste-02-tropical.jpg'],['classico','Clássico','assets/images/taste-03-classico.png'],['boho chic','Boho Chic','assets/images/taste-04-boho-chic.png'],['minimalista','Minimalista','assets/images/taste-05-minimalista.jpg'],['vintage','Vintage','assets/images/taste-06-vintage.png'],['toscana','Toscana','assets/images/taste-07-toscana.jpg']];
const communication=[['minimalista','Minimalista','assets/images/taste-08-minimalista.png'],['sofisticado','Sofisticado','assets/images/taste-09-sofisticado.png'],['romantico','Romântico','assets/images/taste-10-romantico.png'],['leveza','Leveza','assets/images/taste-11-leveza.png'],['criativo','Criativo','assets/images/taste-12-criativo.png']];
const details=[['fineline','Fine Line','assets/images/taste-13-fineline.png'],['aquarela','Aquarela','assets/images/taste-14-aquarela.png'],['nenhum','Nenhum',null]];
const typography=[['classico com serifa','Clássico com serifa','assets/images/taste-15-serif.png'],['moderno sem serifa','Moderno sem serifa','assets/images/taste-16-sans.png'],['escrito a mão','Escrito à mão / caligrafia','assets/images/taste-17-script.png'],['serifa minuscula','Serifa minúscula','assets/images/taste-18-lowercase-serif.png']];
const nameTypography=[['manuscrita','Fonte manuscrita','assets/images/taste-19-name-script.png'],['nao manuscrita','Fonte não manuscrita (serifada)','assets/images/taste-20-name-non-script.png']];
const steps=[
 ['Sobre vocês',[['brideName','Seu nome','text',true],['email','Seu e-mail','email',true],['couple','Nome dos noivos','text',true],['nameNotes','Existe alguma observação em relação ao(s) nome(s)?','textarea',false,'Ex.: Quero usar meu apelido ou somente o primeiro nome.'],['story','Como se conheceram?','textarea'],['together','Há quanto tempo estão juntos?','text'],['personality','Como definem a personalidade do casal?','textarea']]],
 ['Sobre o casamento',[['wedding','Data do casamento','date',true],['venue','Local do casamento','text',true],['city','Cidade','text',true],['time','Horário','time'],['guests','Número aproximado de convidados','number'],['dressCode','Dress Code','singleOptions'],['dressCodeOther','Outro dress code','text']]],
 ['Gostos de monograma',[['monograms','Selecione os estilos de monograma que mais gosta','monogramOptions']]],
 ['Estilo visual',[['visual','Qual o estilo geral do evento?','visualOptions'],['palette','Paleta de Cores Desejada','textarea',false,'Descreva as cores ou o estilo de paleta.'],['avoidColors','Cores que não deseja','text']]],
 ['Comunicação visual',[['identityFeeling','Como gostaria que a identidade visual se comunicasse com os convidados?','communicationOptions']]],
 ['Convite e pequenos detalhes',[['inviteElements','Quais elementos você colocaria no convite?','textarea',false,'Ex.: Flores, folhagens, desenhos, símbolos, iniciais, etc.'],['detailTechnique','Para pequenos detalhes, você prefere aquarela ou fine line?','detailOptions'],['detailTechniqueOther','Outro acabamento','text'],['personalStory','Existe alguma história, frase, ou detalhe pessoal para incluir ou servir de inspiração?','textarea',false,'Ex.: Música especial, símbolo da trajetória, datas importantes ou herança da família.'],['notWanted','Existe algo que você NÃO quer de jeito nenhum na identidade visual?','textarea',false,'Cores, elementos, estilos, referências, etc.']]],
 ['Tipografia',[['fonts','Qual estilo tipográfico traduz a essência do evento?','typographyOptions'],['nameTypography','Para os nomes, você prefere fonte manuscrita ou fonte não manuscrita?','nameTypographyOptions'],['fontOther','Outro estilo tipográfico','text']]],
 ['Referências',[['links','Links de Pinterest, Instagram ou outros sites','textarea'],['likes','O que gosta nas referências?','textarea'],['dislikes','O que não gosta nas referências?','textarea']]],
 ['Comunicação prática',[['channel','Melhor canal de contato','text'],['hours','Melhor horário','text'],['approver','Pessoa responsável pelas aprovações','text'],['additional','Informações adicionais','textarea']]],
 ['Revisão',[]]
];

function render(){document.querySelector('#briefing-app').innerHTML=`<div class="briefing-wrap"><header class="briefing-header"><img class="briefing-logo" src="assets/images/studio-cora-logo.svg" alt="STUDIO CORA"><h1 class="page-title">Vamos criar algo com a cara de vocês</h1><p class="step-copy">${existing?`Olá, ${esc(existing.name.split(' ')[0])}.`:'Conte um pouco sobre o evento para começarmos.'} Suas respostas são salvas automaticamente neste dispositivo.</p></header><section class="briefing-card"><div class="stepper">${steps.map((_,i)=>`<i class="${i<=step?'done':''}"></i>`).join('')}</div><div class="eyebrow">Etapa ${step+1} de ${steps.length}</div><h2 class="section-title" style="margin:8px 0">${steps[step][0]}</h2><div id="step-form">${step===steps.length-1?review():fields()}</div><div class="briefing-actions">${step>0?'<button class="btn btn-ghost" id="back">← Voltar</button>':'<span></span>'}${step<steps.length-1?'<button class="btn btn-primary" id="next">Continuar →</button>':'<button class="btn btn-primary" id="send">Enviar formulário ✦</button>'}</div></section></div>`;document.querySelectorAll('input,textarea,select').forEach(el=>{el.addEventListener('input',capture);el.addEventListener('change',capture)});document.querySelector('#back')?.addEventListener('click',()=>{if(step){step--;render()}});document.querySelector('#next')?.addEventListener('click',()=>{if(validate()){step++;render()}});document.querySelector('#send')?.addEventListener('click',submitForm)}
function capture(e){if(!e.target.name)return;saved[e.target.name]=e.target.type==='checkbox'?[...(saved[e.target.name]||[]).filter(x=>x!==e.target.value),...(e.target.checked?[e.target.value]:[])]:e.target.value;localStorage.setItem(KEY,JSON.stringify(saved))}
function fields(){return `<div class="form-grid">${steps[step][1].map(([name,label,type,req,placeholder])=>{if(type==='monogramOptions')return `<div class="field full"><label>${label}</label>${imageGroup('Aquarela',monograms.aquarela,'checkbox','monograms-aquarela')}${imageGroup('Liso',monograms.liso,'checkbox','monograms-liso')}<p class="step-copy">Você pode escolher vários dentro de um mesmo grupo: Aquarela ou Liso.</p></div>`;if(type==='visualOptions')return `<div class="field full"><label>${label}</label>${imageGroup('',visualStyles,'checkbox','visual')}</div>`;if(type==='communicationOptions')return `<div class="field full"><label>${label}</label>${imageGroup('',communication,'checkbox','communication')}</div>`;if(type==='detailOptions')return `<div class="field full"><label>${label}</label>${imageGroup('',details,'radio','detailTechnique')}</div>`;if(type==='typographyOptions')return `<div class="field full"><label>${label}</label>${imageGroup('',typography,'checkbox','fonts')}</div>`;if(type==='nameTypographyOptions')return `<div class="field full"><label>${label}</label>${imageGroup('',nameTypography,'radio','nameTypography')}</div>`;if(type==='singleOptions')return `<div class="field full"><label>${label}</label><div class="option-grid">${['Esporte','Esporte fino','Passeio','Passeio completo','Black tie','Temático'].map(o=>`<label class="option"><input type="radio" name="${name}" value="${o}" ${saved[name]===o?'checked':''}>${o}</label>`).join('')}</div></div>`;return `<div class="field ${type==='textarea'?'full':''}"><label>${label}${req?' <span>*</span>':''}</label>${type==='textarea'?`<textarea name="${name}" placeholder="${placeholder||''}" ${req?'required':''}>${esc(saved[name]||'')}</textarea>`:`<input name="${name}" type="${type}" placeholder="${placeholder||''}" ${req?'required':''} value="${esc(saved[name]||'')}">`}</div>`}).join('')}</div>`}
function imageGroup(title,items,type,name){return `${title?`<div class="taste-group"><h3>${title}</h3>`:''}<div class="image-choice-grid choice-${name}">${items.map(([value,label,src])=>`<label class="image-choice"><input type="${type}" name="${name}" value="${value}" ${type==='checkbox'?(saved[name]||[]).includes(value)?'checked':'':saved[name]===value?'checked':''}><span class="image-choice-frame">${src?`<img src="${src}" alt="Referência visual: ${label}">`:'<span class="image-choice-empty">Sem imagem</span>'}</span><strong>${label}</strong></label>`).join('')}</div>${title?'</div>':''}`}
function validate(){for(const el of document.querySelectorAll('[required]'))if(!el.value){el.focus();toast('Preencha os campos obrigatórios.');return false}return true}
function review(){return `<div class="review-item"><strong>Contato</strong><p>${esc(saved.brideName||'Não preenchido')} · ${esc(saved.email||'')}</p></div><div class="review-item"><strong>Casal e casamento</strong><p>${esc(saved.couple||'Não preenchido')} · ${esc(saved.wedding||'')} · ${esc(saved.venue||'')}</p></div><div class="review-item"><strong>Gostos de monograma</strong><p>${esc([...(saved['monograms-aquarela']||[]),...(saved['monograms-liso']||[])].join(', ')||'Nenhum selecionado')}</p></div><div class="review-item"><strong>Estilo e comunicação</strong><p>${esc((saved.visual||[]).join(', '))} · ${esc((saved.communication||[]).join(', '))}</p></div><div class="review-item"><strong>Detalhes e tipografia</strong><p>${esc(saved.detailTechnique||'')} · ${esc((saved.fonts||[]).join(', '))} · Nomes: ${esc(saved.nameTypography||'')}</p></div><div class="review-item"><strong>Direcionamento</strong><p>${esc(saved.inviteElements||'')}<br>${esc(saved.notWanted||'')}</p></div><aside class="remember-banner"><h3>Lembre-se 🤍</h3><p>Oiii! Estamos muito felizes em fazer parte de um momento tão especial na história de vocês! 🤍 Cada identidade visual é criada com muito carinho e de forma personalizada, a partir do briefing, das referências e de tudo o que conversamos sobre o casamento, sempre buscando construir algo único e cheio de significado.</p><p>As referências são super bem-vindas e nos ajudam a entender melhor o estilo que vocês imaginam. Porém, não realizamos ajustes de revisões feitas por Inteligência Artificial e também não reproduzimos criações feitas por IA, já que muitas vezes elas apresentam resultados que não funcionam da mesma forma dentro de um projeto gráfico real. Lembre-se: “o feito à mão é uma dádiva” &lt;3</p><p>Nosso processo é feito com cuidado em cada detalhe, pensando não apenas em deixar tudo bonito, mas em criar uma identidade visual harmoniosa, especial e que converse com o casamento como um todo. Por isso, contamos com a confiança de vocês no nosso processo criativo para construirmos juntas algo que realmente represente esse momento. ✨</p></aside><label class="option" style="display:block;margin-top:18px"><input type="checkbox" id="confirm"> Confirmo que as informações estão corretas.</label>`}
function submitForm(){if(!document.querySelector('#confirm').checked){toast('Confirme que as informações estão corretas.');return}let client=existing;if(client){Object.assign(client,{name:saved.brideName||client.name,couple:saved.couple||client.couple,email:saved.email||client.email,wedding:saved.wedding||client.wedding,venue:saved.venue||client.venue,briefing:'Completo',briefingData:{...saved}})}else{client={id:uid('c'),name:saved.brideName||saved.couple.split('&')[0].trim(),couple:saved.couple,email:saved.email,wedding:saved.wedding,venue:[saved.venue,saved.city].filter(Boolean).join(' · '),progress:0,status:'Novo briefing',briefing:'Completo',briefingData:{...saved},last:'Agora',avatar:(saved.brideName||saved.couple).split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase(),items:0,tasks:[],notes:''};data.clients.push(client)}data.notifications.unshift({id:uid('n'),text:`Novo briefing recebido de ${client.name}`,time:'agora',type:'briefing'});saveData(data);localStorage.setItem(KEY,JSON.stringify(saved));document.querySelector('#briefing-app').innerHTML=`<div class="briefing-wrap"><section class="briefing-card" style="text-align:center;padding:60px 25px"><div style="font-size:42px;color:var(--olive)">✦</div><h1 class="page-title">Formulário enviado com carinho</h1><p class="step-copy">Obrigada por compartilhar tantos detalhes. A STUDIO CORA recebeu o briefing de ${esc(client.couple)} e em breve entraremos em contato.</p></section></div>`}
async function boot(){data=await hydrateData(SEED);params=new URLSearchParams(location.search);existingId=params.get('cliente');existing=existingId?data.clients.find(c=>c.id===existingId):null;KEY=`briefing-${existingId||'novo'}`;saved=JSON.parse(localStorage.getItem(KEY)||JSON.stringify(existing?.briefingData||{}));render()}
boot();
